apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-app
    release: hello-world-app
  name: hello-world-app
spec:
  ports:
  - name: api
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: client
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: hello-world-app
    release: hello-world-app
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-world-app
    release: hello-world-app
  name: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
      release: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
        release: hello-world-app
    spec:
      containers:
      - env:
        - name: TO_BE_MODIFIED
          value: 0P7V0JDUWO8X257OOZYTYY9ZFPCLEMVQ
        - name: ADMIN_EMAIL
          value: test
        - name: ADMIN_PASSWORD
          value: "123"
        - name: API_HOST
          value: http://localhost:3000
        - name: ENABLE_TOS_SECURE_CHANGE
          value: TEST
        - name: END_COMPANY
          value: test
        - name: MONTHS
          value: kurwa
        - name: VENDOR_COMPANY
          value: test
        image: reversaidx/nodejs-test:v2
        imagePullPolicy: IfNotPresent
        name: hello-world-app
        ports:
        - containerPort: 3000
          name: api
          protocol: TCP
        - containerPort: 4000
          name: client
          protocol: TCP
        resources: {}
      - image: mongo:latest
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo-default
